name: Update Data From LFX
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jmertic/lfx-tac-actions@main
        with:
          updateprojects: false
          updatetacmembers: false
          updatetacagendaitems: false
          updateclomonitor: false
          updatedecks: true
          updatecharters: true
          slug: aswf
          overview_decks: '[{"url": "https://docs.google.com/presentation/d/1V7fDPMvDR5rkAjx5f74vyMpkY_tp1hVq/edit?usp=sharing&ouid=108330571292091021915&rtpof=true&sd=true","filename": "ASWF High Level Overview"},{"url":"https://docs.google.com/presentation/d/1DymqK796EhxkLIchx7sNxJloovYLGJD8UDkOdkS42to/edit?usp=sharing","filename": "ASWF Governing Board Overview"},{"url":"https://docs.google.com/presentation/d/1qY9DPLw4aucqIdqqB1_Pi-qKEyIg2V7q9B96-G1jhqE/edit?usp=sharing","filename": "ASWF TAC Overview"},{"url":"https://docs.google.com/presentation/d/1p0FoFJ7-IdDejisJPUYdq_uApn3XW3wJ/edit?usp=sharing&ouid=108330571292091021915&rtpof=true&sd=true","filename":"ASWF Membership Overview"}]'
        env:
          token: ${{ secrets.PAT }} 
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

